[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "express-relay-searcher-utils"
version = 0.0.1
description = "Utilities for searchers to interact with the express relay protocol."
license = "Proprietary"
readme = "README.md"